name: Frontend Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-step:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/build.yaml

  deploy-step:
    needs: build-step
    runs-on: ubuntu-latest
    uses: ./.github/workflows/deploy.yaml
    with:
      ref: ${{ github.ref }}
    secrets: inherit
